version: '3'
services:
  node:
    image: remotedaq_node
    container_name: remotedaq_node
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./remoteDAQ.py:/rdaq-node/remoteDAQ.py:ro
      - ./.env:/rdaq-node/.env:ro
      - ./logs:/rdaq-node/logs
    privileged: true