version: '3'
services:
  node:
    image: remotedaq_node
    container_name: remotedaq_node
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./daq-drivers/advantech/libs/libbiodaq.so:/usr/lib/libbiodaq.so:ro
      - ./daq-drivers/advantech/libs/libbiodaqutil.so:/usr/lib/libbiodaqutil.so:ro
    privileged: true